version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    profiles: 
      - dev

  blog-api:
    build:
      context: ./blog
    ports:
      - "8001:8000"
    depends_on:
      - postgres-db
    environment:
      DEBUG_PROD: "False"
      DEBUG_DEV: "True"
      DB_NAME: "blog"
      DB_USER: "blog"
      DB_PASSWORD: "blog"
      DB_HOST: "postgres-db"
      DB_PORT: 5432
      SECRET_KEY: 'django-insecure-h++jvb2=id5!lxt2cofr^y^6+s)vpa(@7c6u36+u%7qformts!'
      
    profiles: 
      - dev