# Generated by Django 5.0.6 on 2024-06-18 08:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_temp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('picture', models.TextField(blank=True, null=True)),
                ('make_at', models.DateField(default=datetime.date)),
                ('autho_of_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_temp.post')),
            ],
        ),
    ]
