# Generated by Django 5.0.6 on 2024-06-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_temp', '0003_post_dislike_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fields',
            new_name='friends',
        ),
    ]
